[username]
format = " [╭─$user]($style) in "
style_user = "bold cyan"
show_always = true

[directory]
style = "bold yellow"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"
repo_root_style = "bold red"

[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_branch]
symbol = " "
style = "bold red"

[nodejs]
symbol = "⬢ "

[python]
style = "bold blue"

[c]
symbol = " "
style = "bold blue"

# Prompt
[shell]
format = " [$indicator]($style)"
style = "bold dimmed yellow"
bash_indicator = "bash"
fish_indicator = ""
disabled = false

[character]
success_symbol = "[──](bold cyan)[λ](bold green)"
error_symbol = "[──](bold cyan)[λ](bold red)"

[cmd_duration]
disabled = true

